### ISSUE TITLE
Error while running IGT

### ISSUE THREAD

**Issue by NarinderBrar** [doerlbh/mentalRL#1]
Hi, I was testing the source code, It's very interesting research and did good work. But while running your code, I am facing some errors. 

The output of console is the following.

C:\Anaconda3\envs\mentalRLENV\lib\site-packages\seaborn\distributions.py:369: UserWarning: Default bandwidth for data is 0; skipping density estimation.
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "run_IGT.py", line 38, in <module>
    fig, scores, rewards, actions = plotAgents(reports,names,nTrials,reward_functions,labels,fig_name+'_1.png',isIGT=True,plotShortTerm=True)
  File "E:\Projects\Projects_Chitkara\Simulators\mentalRL\IGT\utils\vis.py", line 255, in plotAgents
    fig.savefig(fig_name)
  File "C:\Anaconda3\envs\mentalRLENV\lib\site-packages\matplotlib\figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "C:\Anaconda3\envs\mentalRLENV\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 81, in print_figure
    super().print_figure(*args, **kwargs)
  File "C:\Anaconda3\envs\mentalRLENV\lib\site-packages\matplotlib\backend_bases.py", line 2217, in print_figure
    **kwargs)
  File "C:\Anaconda3\envs\mentalRLENV\lib\site-packages\matplotlib\backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "C:\Anaconda3\envs\mentalRLENV\lib\site-packages\matplotlib\backends\backend_agg.py", line 512, in print_png
    dpi=self.figure.dpi, metadata=metadata, pil_kwargs=pil_kwargs)
  File "C:\Anaconda3\envs\mentalRLENV\lib\site-packages\matplotlib\image.py", line 1601, in imsave
    image.save(fname, **pil_kwargs)
  File "C:\Anaconda3\envs\mentalRLENV\lib\site-packages\PIL\Image.py", line 2155, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: './figures/IGT_1_1.png'

Please take a look and suggest if something wrong from my side. 
Thanks

**Comment by doerlbh** [comment]
Hi Narinder,

Thanks for your email and interest to our work. Based on your error, you will have to first create a folder called **figures** in your directory. That should solve the problem.

Best,
Baihan

**Comment by NarinderBrar** [comment]
Thanks, Its solved
